name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # --------------------------------- Stage 1: Lint -----------------------------------
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install ruff
        run: pip install ruff==0.12.0

      - name: Run linter
        run: ruff check src/ tests/ --output-format=grouped

  # --------------------------------- Stage 2: Tests -----------------------------------
  test-matrix:
    name: Run Python Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run tests with pytest
        run: pytest tests/ -v --tb=short --cov=src --cov-report=xml --cov-report=term-missing --cov-fail-under=10 --junitxml=junit/test-results-${{ matrix.python-version }}.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: coverage.xml

  test-summary:
    name: Tests & Coverage
    runs-on: ubuntu-latest
    needs: test-matrix
    steps:
      - name: Aggregate Test Results
        run: echo "All matrix tests passed successfully."

  # --------------------------------- Stage 3: Security -----------------------------------
  security:
    name: Dependency Scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Scan for vulnerabilities
        # Ignoring NLTK 3.9.3 vulnerabilities that specifically target the WordNet Browser app which is not used in ScholarLens.
        run: pip-audit -r requirements.txt --desc --ignore-vuln GHSA-rf74-v2fm-23pw --ignore-vuln CVE-2026-33230 --ignore-vuln CVE-2026-33231
